### ISSUE TITLE
change image used for BOLD run in executive summary

### ISSUE THREAD

**Issue by LuciMoore** [DCAN-Labs/infant-abcd-bids-pipeline#12]
Currently, the BOLD images used for each run in the executive summary are slices 0.4, 0.5, and 0.6 from the run. If these slices have motion, then the "Task in T1: and "T1 in Task" images will show banding, which is an immediate QC fail even though the run may still be usable. The BOLD image used should therefore be an average of the BOLD images post-motion correction

**Comment by ericearl** [comment]
@LuciMoore This issue belongs in the executive summary repo, I believe.  Also, it should be noted that an average of the BOLD images post-motion-correction could have a different odd-ness to them.  Like if there was a large motion frame during the run, that would average out into the space surrounding the otherwise fine averaged image.  Perhaps a different approach like excluding FD-censored frames and averaging that way?  After all, executive summary runs after everything else has run and would have this info available.

**Comment by LuciMoore** [comment]
closing issue as it is relevant to executive summary repo
